apiVersion: v1
kind: Pod
metadata:
  name: mycoins
  namespace: site
  labels:
    app: mycoins
spec:
  containers:
  - name: api
    image: kramerscs/mycoins:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000